# Generated by Django 3.1.7 on 2021-03-03 22:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=1)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('horaInicio', models.TimeField(blank=True, null=True)),
                ('horaFim', models.TimeField(blank=True, null=True)),
                ('detalhe', models.TextField()),
            ],
            options={
                'verbose_name': 'Ordem_Serviço',
                'verbose_name_plural': 'Ordens_Servico',
                'ordering': ('data',),
            },
        ),
        migrations.CreateModel(
            name='Serv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, unique=True)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'ordering': ('descricao',),
            },
        ),
    ]
